# This is a basic workflow to help you get started with Actions
# This file is also read by the osx-build-wx script to fetch the
# parameters for a manual build.

name: mac-pwsafe

# Controls when the action will run. Triggers the workflow on all push requests,
# or pull request for the master branch
on:
  push:
#    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
permissions:
  contents: read

jobs:
  build_mac_pwsafe:
    name: Build pwsafe for macOS
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Set build parameters
      # If you need to rebuild wxWidgets for some reason, say you changed the build params, just increment FORCE_REBUILD_WX
      # Some usefull debug parameters:
      # "WX_DEBUG_FLAG=--enable-debug --enable-debug_info"
      # "XCODE_CONFIG=Debug"
      # "XCODE_CONFIG=Debug-no-yubi"
      run: |
        echo "WX_VERS=3.2.2.1" >> $GITHUB_ENV
        echo "WX_SRC_DIR=$HOME/wxWidgets" >> $GITHUB_ENV
        echo "WX_BUILD_DIR=$HOME/wxbuild" >> $GITHUB_ENV
        echo "WX_ARCH=arm64,x86_64" >> $GITHUB_ENV
        echo "WX_DEBUG_FLAG=--disable-debug" >> $GITHUB_ENV
        echo "MACOS_VER_MIN=10.14" >> $GITHUB_ENV
        echo "XCODE_VER=14.0.1" >> $GITHUB_ENV
        echo "XCODE_CONFIG=Release" >> $GITHUB_ENV
        echo "HOST_NCPU=`sysctl -n hw.ncpu`" >>$GITHUB_ENV
        echo "FORCE_REBUILD_WX=7" >> $GITHUB_ENV

    - name: Force compatible Xcode version
      run: sudo xcode-select -s /Applications/Xcode_${XCODE_VER}.app/Contents/Developer

    - name: Print Xcode version in use
      run: xcode-select -p
      
    - name: Install tools for Yubikey build
      run: brew install autoconf automake libtool
      
    - name: Build libyubikey from upstream
      run: |
        git clone https://github.com/Yubico/yubico-c.git
        cd yubico-c
        autoreconf --install
        ./configure --disable-shared --disable-documentation CFLAGS="-O2 -arch arm64 -arch x86_64 -mmacosx-version-min=$MACOS_VER_MIN"
        make -j $HOST_CPU check
        make install

    - name: Build ykpers from upstream
      run: |
        git clone https://github.com/Yubico/yubikey-personalization.git
        cd yubikey-personalization
        autoreconf --install
        ./configure --disable-shared --disable-documentation CFLAGS="-O2 -arch arm64 -arch x86_64 -mmacosx-version-min=$MACOS_VER_MIN"
        make -j $HOST_CPU check
        make install

    - name: Cache wxWidgets build
      id: cache-wxWidgets-build
      uses: actions/cache@v3
      with:
        path: |
          ${{ env.WX_BUILD_DIR }}
          ${{ env.WX_SRC_DIR }}/locale/*mo
        key: wx-${{ env.WX_VERS }}-macOS-${{ env.MACOS_VER_MIN }}-Xcode-${{ env.XCODE_VER }}-build-${{ env.FORCE_REBUILD_WX }}

    - name: Checkout wxWidgets
      if: steps.cache-wxWidgets-build.outputs.cache-hit != 'true'
      run: git clone --branch v$WX_VERS --single-branch https://github.com/wxWidgets/wxWidgets.git $WX_SRC_DIR

    - name: Build wxWidgets
      if: steps.cache-wxWidgets-build.outputs.cache-hit != 'true'
      working-directory: ${{ env.WX_SRC_DIR }}
      run: |
        git -C $WX_SRC_DIR submodule update --init
        rm -rf $WX_BUILD_DIR
        mkdir -p $WX_BUILD_DIR
        cd $WX_SRC_DIR
        # use built-in versions of jpeg, tiff, png, and regex (pcre2) libs to avoid linking with those in /usr/local/opt
        ./configure --enable-universal_binary=$WX_ARCH --prefix=$WX_BUILD_DIR --disable-shared --enable-unicode --with-macosx-version-min=$MACOS_VER_MIN --with-libpng=builtin --with-libjpeg=builtin --with-libtiff=builtin --with-regex=builtin --without-liblzma $WX_DEBUG_FLAG
        make -j $HOST_NCPU
        make install
        du -sh $WX_BUILD_DIR

    - name: Generate and print xcconfigs
      working-directory: ${{ github.workspace }}
      run: |
        Xcode/generate-configs -r $WX_BUILD_DIR/bin/wx-config > Xcode/pwsafe-release.xcconfig
        cat Xcode/pwsafe-release.xcconfig
    
    - name: Build pwsafe
      working-directory: ${{ github.workspace }}
      run: xcodebuild -project Xcode/pwsafe-xcode6.xcodeproj -scheme pwsafe -configuration $XCODE_CONFIG

    - name: Install dependencies for creating dmg
      run: brew install gettext create-dmg

    - name: Install language files and create dmg
      working-directory: install/macosx
      run: make

    - name: Upload artifacts
      uses: 'actions/upload-artifact@v3'
      with:
        name: PasswordSafe.${{ github.sha }}.dmg
        path: pwsafe-universal-*.dmg
        if-no-files-found: error
